### PR TITLE
Fixed test assert 'expected' oder

### PR DESCRIPTION
**Pull request by dritter-hd**
Minor fix of 'expected' test assert order

Further, it seems that the `CsvSortOptions` and up-to-date `CsvExternalSort` as described in the readme are not in the latest `0.4.0` release version.

### CODE REVIEW

**Comment by lemire** [comment]
> Further, it seems that the CsvSortOptions and up-to-date CsvExternalSort as described in the readme are not in the latest 0.4.0 release version.

I do not understand. Can you elaborate? It is certainly there.

**Comment by lemire** [comment]
```
$ zip -Tv externalsortinginjava-0.4.3.zip |grep Csv
    testing: externalsortinginjava-externalsortinginjava-0.4.3/src/main/java/com/google/code/externalsorting/csv/CsvExternalSort.java   OK
    testing: externalsortinginjava-externalsortinginjava-0.4.3/src/main/java/com/google/code/externalsorting/csv/CsvSortOptions.java   OK
    testing: externalsortinginjava-externalsortinginjava-0.4.3/src/test/java/com/google/code/externalsorting/csv/CsvExternalSortTest.java   OK
```

**Comment by lemire** [comment]
Merging.

**Comment by dritter-hd** [comment]
You are right, it is in release version 0.4.3. However, version 0.4.0 seems to be the latest one in https://mvnrepository.com/artifact/com.google.code.externalsortinginjava/externalsortinginjava. With `[0.1.9,)`, as in the readme, this is the one automatically downloaded.

**Comment by lemire** [comment]
The maven repository is an unsupported legacy at this point. It will randomly accept artifacts, often dropping them on the floor... there is no support. If you use maven, I recommend setting your own repository.

**Comment by lemire** [comment]
(If you have any proposals, I am a taker. We moved to JCenter for other projects... but it is unclear, what if anything works for people.)

**Comment by dritter-hd** [comment]
So far I was not aware of problems of that kind. Let me contact you directly in the next days to understand your issue with maven central. I am happy to help, if possible.

**Comment by lemire** [comment]
The issue is really simple: we do a release, the artifacts get uploaded to the maven repository... but then they never appear.

**Comment by gecec** [comment]
> Minor fix of 'expected' test assert order

Sorry, my fault.

**Comment by dritter-sap** [comment]
@gecec no worries! @lemire: could this have caused issues for you as well: https://issues.sonatype.org/browse/MVNCENTRAL-1440? I am eager to help and would like to see it in maven central, if possible.

**Comment by lemire** [comment]
Maven central is software from another era. It is breaks all the time. It is terribly slow. The issue you point is not an isolated case. It is common. It can take days or weeks for the artifact to show up, and sometimes they never do.

> I am eager to help and would like to see it in maven central, if possible.

I will take the help. How do you propose to help?

See: that's the problem... there is not much one can do. You release the artifacts and you wait.

If you have some better approach... I am eager for it...

**Comment by lemire** [comment]
@dritter-sap For example, is there any way to track where the artifacts are... what is their current state... You see that the releases up to 0.4.0 showed up... Then 0.4.1, 0.4.2, 0.4.3, 0.4.4 are missing. Why? How could you tell?

You can see that I did the release. The release process is super simple: "maven release:clean release:prepare release:perform". I see the artifacts getting uploaded to maven central... if they don't get uploaded, then the process fails and I have to restart.

So I know they got the artifacts.

But I have no way of tracking them afterward.

They have this terrible GUI tool from 1990... it claims that we have 0.4.0 and 0.4.4 (but note that 0.4.4 is not available yet as far as I can tell). What happened to 0.4.1, 0.4.2, 0.4.3? No trace. But they did get the artifacts. I guess they got lost.

Screen Shot 2020-04-20 at 10 40 09 PM

There is nothing outstanding anywhere...


Screen Shot 2020-04-20 at 10 41 32 PM

**Comment by lemire** [comment]
@dritter-sap  So my advice is "be patient". It may show up soon... or a bit later... or...


I can assure you that they got the artifacts.

**Pull request merged**
