### PR TITLE
Java9plus

### PR DESCRIPTION
**Pull request by joehei**
Module info for java 9+

### CODE REVIEW

**Comment by lemire** [comment]
@joehei The PR appears to break our tests. Can you have a look?

**Comment by joehei** [comment]
Maybe this is worth a try:

https://maven.apache.org/plugins/maven-compiler-plugin/examples/module-info.html

**Comment by lemire** [comment]
@joehei

So the fix is to instruct maven to omit the file? Do I get this right?

**Comment by joehei** [comment]
Hi, 
Yes the compilation has to be triggered twice, once for java 9 only the module-info.java and once for all other classes with java 1.8.

In the example links you find two executions Blocks you have to set source / target to 1.8

**Comment by lemire** [comment]
@joehei When I release the code, there is just one compilation and thus there is just one jar uploaded to Maven which will have to be the one which omit the new module file. Correct?

**Comment by lemire** [comment]
I don't know, maybe it is fine to release to maven the Java 8 version, but then I'd like to know how we benefit from having having a module file that won't get distributed via maven.

**Comment by WellingR** [comment]
I have never used this myself, but it is possible to package separate classes for different java versions in a single jar.

see https://maven.apache.org/plugins/maven-compiler-plugin/multirelease.html

**Comment by lemire** [comment]
Yes, this is done in https://github.com/RoaringBitmap/RoaringBitmap  but there was a purpose to it: get better performance.

Right now, I am not exactly sure what the case is for bringing module info. into the project, especially if we are not going to release it in the end. It is certainly not about getting better performance.

cc @richardstartin

**Comment by lemire** [comment]
I am going to close this since the benefits are unclear. Please open a new pull request if there is a rationale for it.

**Pull request closed without merging**
