### PR TITLE
Including csv External sorting using apache commons

### PR DESCRIPTION
**Pull request by guilhermefaleixo**
Including new class to deal with CsvExternal sorting using apache commons csv

I made small changes into your logic to be able to work with csv files better.

### CODE REVIEW

**Comment by lemire** [comment]
@guilhermefaleixo Can you review the warnings at LGTM

https://lgtm.com/projects/g/lemire/externalsortinginjava/rev/pr-a4593dbe5b747ee2d5eb5c237f9d3bef6834ac86

And make sure that they are not a concern?

**Comment by guilhermefaleixo** [comment]
Hello @lemire  the LGTM is down right now, but one of the issues is the inputStream that is not closed but it is the same code that you have in that part and the second issue as far as I am concern it is not an issue as it will be closed anyway when the parser is closed.

**Comment by lemire** [comment]
Ok. Let us merge.

**Comment by guilhermefaleixo** [comment]
Thank you so much for your great work @lemire , your library helped me a lot and I hope that this CSV version of it can help as much as helped me =D

**Pull request merged**
